name: pyoe_examples
channels:
- conda-forge
- default
dependencies:
- python>=3.6
- nb_conda
- numpy
- matplotlib
- scipy
- pandas
- xarray
- uncertainties
- seaborn
- pip
- cython
- dask
- netcdf4
- numba
- gcc_linux-64
- gfortran_linux-64
- fftw
- lapack
- pip:
  # - pyOptimalEstimation
  # - git+git://github.com/maahn/pamtra2.git@7d4cb2feb42342b5bdf088b08fbf9ccacfce08aa
  - git+git://github.com/maahn/pamtra2.git
  - git+git://github.com/maahn/pyOptimalEstimation.git